# Copyright © 2014 Bart Massey
# Makefile for int_list_demo

CPP = g++
CC = gcc
CFLAGS = -g -Wall
CPPFLAGS = $(CFLAGS)

OBJS = intlist.o int_list.o int_node.o int_list_demo.o

int_list_demo: $(OBJS)
	$(CPP) $(CPPFLAGS) -o int_list_demo $(OBJS)

int_list_demo.o: intlist.h int_list.h int_node.h

intlist.o: intlist.h

int_list.o: int_list.h

int_node.o: int_node.h
